//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediska.Models
{
    using System;
    
    public partial class cmplxCustomerInfoByID
    {
        public int ID { get; set; }
        public string custusrMobileNo { get; set; }
        public bool custusrPasswordMustChange { get; set; }
        public bool custusrActivated { get; set; }
        public string custusrManagerName { get; set; }
        public string custusrManagerFamily { get; set; }
        public bool custusrManagerGender { get; set; }
        public string custusrAuthCode { get; set; }
        public Nullable<System.DateTime> custusrAuthCodeExpireDate { get; set; }
        public string custusrOTP { get; set; }
        public string custusrOTPGUID { get; set; }
        public Nullable<System.DateTime> custusrChangePasswordDateTime { get; set; }
        public System.DateTime NowDate { get; set; }
        public string custusrChangePasswordGUID { get; set; }
        public string custusrPassword { get; set; }
        public Nullable<System.DateTime> custusrOTPDateTime { get; set; }
    }
}
