//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediska.Models
{
    using System;
    
    public partial class cmplxPackagePicture
    {
        public int ID { get; set; }
        public int pkgpicPackageID { get; set; }
        public string pkgpicBeforePicText { get; set; }
        public string pkgpicPictureFileName { get; set; }
        public string pkgpicAfterPicText { get; set; }
        public int pkgpicOrder { get; set; }
    }
}
