//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediska.Models
{
    using System;
    
    public partial class cmplxProductPicture
    {
        public int ID { get; set; }
        public int prdpicProductID { get; set; }
        public string prdpicBeforePicText { get; set; }
        public string prdpicPictureFileName { get; set; }
        public string prdpicAfterPicText { get; set; }
        public int prdpicOrder { get; set; }
    }
}
