//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediska.Models
{
    using System;
    
    public partial class cmplxGetMyContracts
    {
        public int CustomerID { get; set; }
        public int ContractID { get; set; }
        public int ProductID { get; set; }
        public string OffCode { get; set; }
        public int PackageID { get; set; }
        public string customerCompanyName { get; set; }
        public string ManagerFullName { get; set; }
        public string prdxtraTitle { get; set; }
        public string prdxtraAvatarPhotoName { get; set; }
        public string prdxtraMainPhotoName { get; set; }
        public Nullable<bool> prdxtraNeedOnlineLicense { get; set; }
        public string prdxtraOnlineLicense1Title { get; set; }
        public string prdxtraOnlineLicense2Title { get; set; }
        public decimal contractPrice { get; set; }
        public decimal contractOffPrice { get; set; }
        public decimal contractFinalPrice { get; set; }
        public string contractOnlineLicense1 { get; set; }
        public string contractOnlineLicense2 { get; set; }
        public string contractHardLockID { get; set; }
        public System.DateTime contractDate { get; set; }
        public string packageName { get; set; }
        public decimal conpackPrice { get; set; }
        public decimal conpackOffPrice { get; set; }
        public decimal conpackFinalPrice { get; set; }
        public Nullable<bool> contractCustomerAcceptLicense { get; set; }
    }
}
