//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediska.Models
{
    using System;
    
    public partial class cmplxSMSSetting
    {
        public string setSMSCenterWebServiceAddress { get; set; }
        public string setSMSCenterUserName { get; set; }
        public string setSMSCenterPassword { get; set; }
        public string setSMSCenterFromNo { get; set; }
    }
}
