//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediska.Models
{
    using System;
    
    public partial class cmplxProduct
    {
        public int ID { get; set; }
        public int prdxtraProductID { get; set; }
        public string prdxtraTitle { get; set; }
        public string prdxtraShortDesc { get; set; }
        public string prdxtraFullDesc { get; set; }
        public string prdxtraAvatarPhotoName { get; set; }
        public string prdxtraMainPhotoName { get; set; }
        public bool prdxtraHasOff { get; set; }
        public decimal prdxtraOffPercent { get; set; }
        public Nullable<System.DateTime> prdxtraOffStartDate { get; set; }
        public Nullable<System.DateTime> prdxtraOffEndDate { get; set; }
        public string prdxtraCatalogFileName { get; set; }
        public string CategoryClassName { get; set; }
        public Nullable<bool> HasOff { get; set; }
        public decimal productPrice { get; set; }
        public string prdxtraPlatform { get; set; }
        public Nullable<int> prdxtraFreeBackupMonth { get; set; }
        public string packageName { get; set; }
        public Nullable<int> PackageCount { get; set; }
        public Nullable<int> PackageID { get; set; }
    }
}
