//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediska.Models
{
    using System;
    
    public partial class cmplxPackage
    {
        public int ID { get; set; }
        public string packageName { get; set; }
        public decimal packagePrice { get; set; }
        public decimal packageRasmiPrice { get; set; }
        public Nullable<byte> packagePartitionIndex { get; set; }
        public int packageProductID { get; set; }
    }
}
